version: '3.7'

services:
  app:
    build: .
    image: django_testing_svc
#    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    command: bash -c "python3.6 manage.py runserver 0.0.0.0:8000"
#    depends_on:
#      - db
    volumes:
      - .:/app
    working_dir: /app
    expose:
      - 8000
    ports:
      - 8000:8000
      - 5431:5431
    environment:
      - LOG_LEVEL=DEBUG
      - DJANGO_DEBUG=true
      - DJANGO_SECRET_KEY=wo(^@!8@u1*pp-(viudubp6ytc@dyietnj&s+f+2i94^s9h2g#
#      - MYSQL_DATABASE=ddivesvc
#      - MYSQL_USER=root
#      - MYSQL_PASSWORD=IAMROOTPASSWORD
#    env_file:
#      - ./.env.dev